imgsz: [160, 120]
nc: 3
names:
  0: Rock
  1: Paper
  2: Scissors

preprocess:
  adaptive_equalization: false
  clahe_clip_limit: 2.0
  clahe_tile_grid_size: [8, 8]

model:
  channels: [24, 48, 96]
  hidden: 128
  dropout: 0.1
  se_ratio: 0.25
